name: Create CI images

on:
  push:
    branches: [ 'main' ]
    paths:
      - '*.yml'
      - 'Dockerfile'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, i686, aarch64 ]
        version: [
          #13.0.1,
          #14.0.6,
          15.0.7,
        ]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "386,arm64"

      - name: Parse Semver
        uses: booxmedialtd/ws-action-parse-semver@v1.4.7
        id: semver_parser
        with:
           input_string: ${{ matrix.version }}

      - name: Build and push image
        uses: docker/build-push-action@v4.0.0
        env:
          version_key: ${{ env.REGISTRY }}/${{ github.repository_owner }}/manylinux2014_${{ matrix.arch }}-llvm
        with:
          context: .
          push: true
          tags: ${{ env.version_key }}:${{ steps.semver_parser.outputs.fullversion }},${{ env.version_key }}:${{ steps.semver_parser.outputs.major }}.x
          build-args: |
            LLVM_TAG=llvmorg-${{ matrix.version }}
            ARCH=${{ matrix.arch }}
